// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsrzrcrfhgsuwyqkgfke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzcnpyY3JmaGdzdXd5cWtnZmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0OTI1MTcsImV4cCI6MjA1NDA2ODUxN30.3s43vTjAYaas4gxw-GQFXp1lTxEvUKqjmKRjBetVJWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);